stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  image: rust:latest
  script:
    - cargo fmt --all -- --check

test:
  stage: test
  image: rust:latest
  script:
    - cargo test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t mille055/projectf:latest .
    - docker push mille055/projectf:latest
  only:
    - main

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker pull mille055/projectf:latest
    - docker run -d -p 8000:8000 mille055/projectf:latest
  only:
    - main
